// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StorageWebAPP.Models;

#nullable disable

namespace StorageWebAPP.Data
{
    [DbContext(typeof(StorageContext))]
    [Migration("20211115132358_Balancev2")]
    partial class Balancev2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("StorageWebAPP.Models.AccountModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "General manager"
                        });
                });

            modelBuilder.Entity("StorageWebAPP.Models.BalanceModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MovementTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NomenclatureId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResponsibleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Balance");
                });

            modelBuilder.Entity("StorageWebAPP.Models.MovementTypeModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MovementType");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Obtaining"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Consumption"
                        });
                });

            modelBuilder.Entity("StorageWebAPP.Models.NomenclatureModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Measure")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Nomenclature");
                });
#pragma warning restore 612, 618
        }
    }
}
